<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.1;netstandard2.0;net35;net40;net45;net462;netcoreapp3.0;net10.0;net11.0</TargetFrameworks>
		<AssemblyName>WinDivertSharp</AssemblyName>
		<PackageId>Aigio.WinDivertSharp</PackageId>
		<!-- major.minor.build-preview.revision.yyMM0.{num}dd -->
		<Version>1.4.3-preview.3.26080.230</Version>
		<Authors>https://github.com/AigioL</Authors>
		<GeneratePackageOnBuild Condition="'$(Configuration)' == 'Release'">true</GeneratePackageOnBuild>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<PackageLicenseExpression>LGPL-3.0-only</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/AigioL/Common/tree/main/src/WinDivertSharp.Shared</PackageProjectUrl>
		<RepositoryUrl>https://github.com/AigioL/Common.git</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>WinDivert packet-sniffer packet firewall divert-sockets packet-capture</PackageTags>
		<PackageReleaseNotes>Changes this to an unsafe library. Users must now enable unsafe code and perform raw pointer access, just like using the real native library. The reason for this is that we're getting mysterious errors that I can't even be bothered to attempt to fully understand by holding the user's hand like a baby and trying to hide pointer access away from them. If a user doesn't know to perform null checks, or thinks that there's such a thing as "safe" code, then they simply need to go away and hush now.</PackageReleaseNotes>
		<Description>A safe, minimal .NET binding over WinDivert</Description>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<PackageOutputPath>$(MSBuildProjectDirectory)\..\artifacts\pkg</PackageOutputPath>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<Import Project="..\WinDivertSharp.Shared\WinDivertSharp.Shared.projitems" Label="Shared" />

	<ItemGroup>
		<PackageReference Include="System.Memory" Condition="'$(TargetFramework)' == 'netstandard1.1' OR '$(TargetFramework)' == 'netstandard2.0' OR ($(TargetFramework.StartsWith('net462')))" />
	</ItemGroup>

	<ItemGroup>
		<None Include="$(MSBuildThisFileDirectory)..\WinDivertSharp.Shared\LICENSE" Pack="true" PackagePath="\" />
		<None Include="$(MSBuildThisFileDirectory)..\WinDivertSharp.Shared\LICENSE.WINDIVERT" Pack="true" PackagePath="\" />
		<None Include="$(MSBuildThisFileDirectory)..\WinDivertSharp.Shared\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

</Project>
