<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.1;net$(DotNet_Version_LTS);net$(DotNet_Version_STS)</TargetFrameworks>
		<RootNamespace>AigioL.Common.Primitives</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<EmbeddedResource Include="..\..\res\i18n\District\Resources.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
			<LinkBase>Properties</LinkBase>
			<CustomToolNamespace>AigioL.Common.Primitives.District.Properties</CustomToolNamespace>
		</EmbeddedResource>
		<EmbeddedResource Include="..\..\res\i18n\District\Resources.*.resx">
			<LinkBase>Properties</LinkBase>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<Compile Include="..\..\res\i18n\District\Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
			<LinkBase>Properties</LinkBase>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MemoryPack" />
	</ItemGroup>

</Project>
